services:
  database:
    image: mongo
    environment:
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
      - DB_NAME=${DB_NAME}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./config/mongo:/docker-entrypoint-initdb.d
    networks:
      - internal
    ports:
      - ${DB_PORT}:${DB_PORT}

  frontend:
    image: fontend
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        APP_BACKEND_INNER_HOST: ${APP_BACKEND_INNER_HOST}
        APP_BACKEND_PORT: ${APP_BACKEND_PORT}
        PORT: ${APP_FRONTEND_PORT}
    working_dir: /app
    volumes:
      - ./apps/web/src:/app/apps/web/src:ro
    networks:
      - internal
    ports:
      - ${APP_FRONTEND_PORT}:${APP_FRONTEND_PORT}

  backend:
    image: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PSWD: ${DB_PSWD}
        DB_NAME: ${DB_NAME}
        PORT: ${APP_BACKEND_PORT}
    working_dir: /app
    volumes:
      - ./apps/backend/src:/app/apps/backend/src:ro
    networks:
      - internal
    ports:
      - ${APP_BACKEND_PORT}:${APP_BACKEND_PORT}

networks:
  internal: {}
